"""Add UrlAnalysisJob

Revision ID: 1da5bdf81416
Revises: e7a3737e60e2
Create Date: 2026-03-07 13:29:26.963846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da5bdf81416'
down_revision: Union[str, Sequence[str], None] = 'e7a3737e60e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['source_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_url_analysis_jobs_created_at', 'url_analysis_jobs', ['created_at'], unique=False)
    op.create_index('ix_url_analysis_jobs_status', 'url_analysis_jobs', ['status'], unique=False)
    op.alter_column('source_results', 'query_job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_results', 'query_job_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index('ix_url_analysis_jobs_status', table_name='url_analysis_jobs')
    op.drop_index('ix_url_analysis_jobs_created_at', table_name='url_analysis_jobs')
    op.drop_table('url_analysis_jobs')
    # ### end Alembic commands ###
